### ISSUE TITLE
Self explanation is unsaved if cell is not run first.

### ISSUE THREAD

**Issue by hmashrique** [aolney/self-explanation-extension#3]
**Issue:** 
If a user tries to write and save a self explanation before running the code cell above, it doesnt save. It only saves after the user runs the code cell above first.

[Video link](https://youtu.be/VT4gHZeLXvg) shared for better understanding.

**Comment by aolney** [comment]
I think the problem is that your notebook has "saved state" in that cell that breaks it.

The normal usage would be for a notebook that has no self explanation boxes saved, and these are dynamically added on first use.

[Here is a demo video of it working on my computer](https://youtu.be/yZGJeaWghxc)

I will upload the latest version with other fixes to the server in a moment.

**Comment by sdflem** [comment]
@aolney I am still able to reproduce @hmashrique 's issue, even for notebooks that should have no saved state. I'll plan to show it to you at next meeting.

**Comment by aolney** [comment]
If you sent me a link/tell me which notebook it is, I can try it.

Are you both using Chrome? I doubt that is the issue, but I'm using 86.0.4240.111

**Comment by sdflem** [comment]
I'm using the exact same version of Chrome (86.0.4240.111).

Here's a [video demonstration of me reproducing the bug](https://www.youtube.com/watch?v=_bMsivfpcoA).

**Comment by aolney** [comment]
I can replicate with one of E1 template notebooks **if the notebook already has cell output state**. In your example, you can see the output state at this time index https://youtu.be/_bMsivfpcoA?t=98 , specifically the dataframe output.

In my test, when the notebook has cell output state, the button has no attached handler, so pressing it does nothing. I'm really not sure why this would happen since the code that generates the button does so with the handler. My guess is that Jupyter security is stripping out scripts.

You can try it without state using the following steps:

- Open a notebook
- Go to Menu "Edit" -> "Clear all outputs"
- Save the notebook and reload the page
- Then proceed with the test

I think this is valid because users will always be presented with a notebook with no saved output state.

I had to watch your video without sound b/c I'm in a university meeting, so apologies if I missed something important that you said. I'll watch it with sound as soon as I can.

**Comment by sdflem** [comment]
The weird thing is that I was opening notebooks that I'd never opened/ran before. So, why did they already have output state?

**Comment by aolney** [comment]
JupyterLab allows you to save output state with your notebook. Examples are plots and similar output. It makes sense if you have a long running computation that created output, and you want to share that result without forcing the consumer to rerun it.

**Comment by sdflem** [comment]
So, does that mean that the E1 notebooks in GitHub include such state? If so, perhaps we should strip out such state before committing them to the repo?

**Comment by aolney** [comment]
Definitely those will be stripped. Development of those paused while the self-explanation extension was being developed because it was unclear what presentation functionality would be in the notebook and what would be in the extension. Now that this is clear, I believe development of those can continue uninterrupted.

I'll see if I can make a big push on those this weekend.

Feel free to reopen this issue as appropriate.
